import './css/styles.css'

import { Inter, Architects_Daughter } from 'next/font/google'
import Header from '@/components/webstories/Header'
const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap'
})



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode
}) {
  return (
      <html lang="en">
      <title>WebStories</title>
      <body className={`${inter.variable} font-inter antialiased bg-white text-gray-900 tracking-tight`}>
      <div className={`flex flex-col min-h-screen overflow-hidden  bg-neutral-100`}>
        <Header/>
        {children}
      </div>
      </body>
      </html>
  )
}
 