import "./css/styles.css"
import Header from '@/components/automatic-test-Generation/Header'
import { Inter, Architects_Daughter } from 'next/font/google'


const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap'
})

const architects_daughter = Architects_Daughter({
  subsets: ['latin'],
  variable: '--font-architects-daughter',
  weight: '400',
  display: 'swap'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode
}) {
  return (
      <html lang="en">
      <title>Automatic Test Generation</title>
      <body className={`${inter.variable} ${architects_daughter.variable} font-inter antialiased  tracking-tight`}>
      <div className="flex flex-col min-h-screen overflow-hidden">
        <Header/>
        {children}
      </div>
      </body>
      </html>
  )
}
 