FROM mongo:latest

ENV MONGO_INITDB_ROOT_USERNAME=root \
    MONGO_INITDB_ROOT_PASSWORD=pass \
    MONGO_INITDB_DATABASE=animal_db

COPY init-db.js /docker-entrypoint-initdb.d/init-db.js

EXPOSE 27017