name: CI
on: 
  pull_request: 
    branches: 
      - "**"
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install dependencies
        run: |
          npm install
          npm run build
      - name: run Lighthouse CI for the Application
        run: |
          npm install -g @lhci/cli@0.14.x
          lhci autorun --config=lighthouserc.json --collect.url="http://localhost:3000" --collect.startServerCommand="npm run start" --upload.outputDir="./lhci-reports/app"
      - name: run Lighthouse CI for Keploy.io Deployed Website
        run: |
          npm install -g @lhci/cli@0.14.x
          lhci autorun --config=lighthouserc.json --collect.url="https://www.keploy.io" --upload.outputDir="./lhci-reports/keploy.io"
      - name: Compare Lighthouse Reports
        run: |
          node compare-lhci-reports.js