name: CI
on: 
  pull_request: 
    branches: 
      - "**"
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install dependencies
        run: |
          npm install
          npm run build
      - name: run Lighthouse CI for the Application
        run: |
          npm install -g @lhci/cli@0.14.x
          lhci autorun --upload.target=temporary-public-storage --config=../.././lighthouserc.json || echo "LHCI failed!"
      - name: run Lighthouse CI for Deploy Keploy
        run: |
          npm install -g @lhci/cli@0.14.x
          lhci autorun --upload.target=temporary-public-storage --config=../.././lighthouserckeploy.json || echo "LHCI failed!"